package remediator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/aristonllc/stigkube/pkg/models"
)

// Remediator generates Ansible remediation playbooks
type Remediator struct {
	deploymentMethod string
	outputDir        string
}

// New creates a new Remediator
func New(deploymentMethod, outputDir string) *Remediator {
	return &Remediator{
		deploymentMethod: deploymentMethod,
		outputDir:        outputDir,
	}
}

// Generate creates Ansible remediation for failed findings
func (r *Remediator) Generate(result *models.ScanResult) error {
	// Filter to only failed findings
	var failedFindings []models.Finding
	for _, f := range result.Findings {
		if f.Status == models.StatusFail {
			failedFindings = append(failedFindings, f)
		}
	}

	if len(failedFindings) == 0 {
		fmt.Println("No failed findings to remediate")
		return nil
	}

	fmt.Printf("Generating remediation for %d failed controls\n", len(failedFindings))

	// Create output directory structure
	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation")
	if err := os.MkdirAll(filepath.Join(roleDir, "tasks"), 0750); err != nil {
		return fmt.Errorf("failed to create role directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(roleDir, "templates"), 0750); err != nil {
		return fmt.Errorf("failed to create templates directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(roleDir, "defaults"), 0750); err != nil {
		return fmt.Errorf("failed to create defaults directory: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(roleDir, "handlers"), 0750); err != nil {
		return fmt.Errorf("failed to create handlers directory: %w", err)
	}

	// Generate main playbook
	if err := r.generatePlaybook(); err != nil {
		return fmt.Errorf("failed to generate playbook: %w", err)
	}

	// Generate inventory template
	if err := r.generateInventory(); err != nil {
		return fmt.Errorf("failed to generate inventory: %w", err)
	}

	// Generate role files
	if err := r.generateMainTasks(failedFindings); err != nil {
		return fmt.Errorf("failed to generate tasks: %w", err)
	}

	if err := r.generateHandlers(); err != nil {
		return fmt.Errorf("failed to generate handlers: %w", err)
	}

	if err := r.generateDefaults(); err != nil {
		return fmt.Errorf("failed to generate defaults: %w", err)
	}

	// Generate STIG mapping file
	if err := r.generateSTIGMapping(failedFindings); err != nil {
		return fmt.Errorf("failed to generate STIG mapping: %w", err)
	}

	fmt.Printf("Remediation playbook generated at: %s\n", r.outputDir)
	return nil
}

func (r *Remediator) generatePlaybook() error {
	playbook := `---
# StigKube Remediation Playbook
# Generated for deployment method: ` + r.deploymentMethod + `
#
# IMPORTANT: Review all changes before applying!
# Run with --check first: ansible-playbook -i inventory site.yml --check

- name: Apply STIG remediation to Kubernetes cluster
  hosts: control_plane
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Verify Kubernetes is running
      command: kubectl get nodes
      register: kubectl_check
      changed_when: false
      failed_when: kubectl_check.rc != 0

    - name: Backup current configurations
      archive:
        path:
          - /etc/kubernetes/manifests
          - /var/lib/kubelet/config.yaml
        dest: "/root/k8s-backup-{{ ansible_date_time.iso8601_basic_short }}.tar.gz"
      when: stig_backup_configs | default(true)

  roles:
    - stig-remediation

  post_tasks:
    - name: Wait for API server to be ready
      command: kubectl get nodes
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10
      changed_when: false
`

	return os.WriteFile(filepath.Join(r.outputDir, "site.yml"), []byte(playbook), 0600)
}

func (r *Remediator) generateInventory() error {
	inventory := `# StigKube Remediation Inventory
# Update with your actual node hostnames/IPs

[control_plane]
# Add your control plane nodes here
# master1 ansible_host=192.168.1.10 ansible_user=root
# master2 ansible_host=192.168.1.11 ansible_user=root

[workers]
# Add your worker nodes here
# worker1 ansible_host=192.168.1.20 ansible_user=root
# worker2 ansible_host=192.168.1.21 ansible_user=root

[k8s_cluster:children]
control_plane
workers

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
`

	return os.WriteFile(filepath.Join(r.outputDir, "inventory"), []byte(inventory), 0600)
}

func (r *Remediator) generateMainTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# STIG Remediation Tasks\n")
	tasks.WriteString("# Generated by StigKube\n")
	tasks.WriteString("# Deployment Method: " + r.deploymentMethod + "\n\n")

	// Group findings by component
	apiServerFindings := filterByComponent(findings, "api")
	controllerFindings := filterByComponent(findings, "controller")
	schedulerFindings := filterByComponent(findings, "scheduler")
	etcdFindings := filterByComponent(findings, "etcd")
	kubeletFindings := filterByComponent(findings, "kubelet")
	generalFindings := filterByComponent(findings, "general")

	// Include component-specific task files
	if len(apiServerFindings) > 0 {
		tasks.WriteString("- name: Include API Server remediation\n")
		tasks.WriteString("  include_tasks: apiserver.yml\n")
		tasks.WriteString("  tags: [apiserver]\n\n")
		if err := r.generateAPIServerTasks(apiServerFindings); err != nil {
			return err
		}
	}

	if len(controllerFindings) > 0 {
		tasks.WriteString("- name: Include Controller Manager remediation\n")
		tasks.WriteString("  include_tasks: controller-manager.yml\n")
		tasks.WriteString("  tags: [controller-manager]\n\n")
		if err := r.generateControllerManagerTasks(controllerFindings); err != nil {
			return err
		}
	}

	if len(schedulerFindings) > 0 {
		tasks.WriteString("- name: Include Scheduler remediation\n")
		tasks.WriteString("  include_tasks: scheduler.yml\n")
		tasks.WriteString("  tags: [scheduler]\n\n")
		if err := r.generateSchedulerTasks(schedulerFindings); err != nil {
			return err
		}
	}

	if len(etcdFindings) > 0 {
		tasks.WriteString("- name: Include etcd remediation\n")
		tasks.WriteString("  include_tasks: etcd.yml\n")
		tasks.WriteString("  tags: [etcd]\n\n")
		if err := r.generateEtcdTasks(etcdFindings); err != nil {
			return err
		}
	}

	if len(kubeletFindings) > 0 {
		tasks.WriteString("- name: Include Kubelet remediation\n")
		tasks.WriteString("  include_tasks: kubelet.yml\n")
		tasks.WriteString("  tags: [kubelet]\n\n")
		if err := r.generateKubeletTasks(kubeletFindings); err != nil {
			return err
		}
	}

	if len(generalFindings) > 0 {
		tasks.WriteString("- name: Include general cluster remediation\n")
		tasks.WriteString("  include_tasks: general.yml\n")
		tasks.WriteString("  tags: [general]\n\n")
		if err := r.generateGeneralTasks(generalFindings); err != nil {
			return err
		}
	}

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "main.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateAPIServerTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# API Server STIG Remediation\n\n")

	manifestPath := r.getManifestPath("kube-apiserver")

	for _, f := range findings {
		tasks.WriteString(fmt.Sprintf("# %s - %s\n", f.Control.ID, f.Control.Title))
		tasks.WriteString(fmt.Sprintf("# Expected: %s\n", f.ExpectedValue))

		task := r.generateManifestPatchTask(f, manifestPath)
		tasks.WriteString(task)
		tasks.WriteString("\n")
	}

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "apiserver.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateControllerManagerTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# Controller Manager STIG Remediation\n\n")

	manifestPath := r.getManifestPath("kube-controller-manager")

	for _, f := range findings {
		tasks.WriteString(fmt.Sprintf("# %s - %s\n", f.Control.ID, f.Control.Title))
		task := r.generateManifestPatchTask(f, manifestPath)
		tasks.WriteString(task)
		tasks.WriteString("\n")
	}

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "controller-manager.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateSchedulerTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# Scheduler STIG Remediation\n\n")

	manifestPath := r.getManifestPath("kube-scheduler")

	for _, f := range findings {
		tasks.WriteString(fmt.Sprintf("# %s - %s\n", f.Control.ID, f.Control.Title))
		task := r.generateManifestPatchTask(f, manifestPath)
		tasks.WriteString(task)
		tasks.WriteString("\n")
	}

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "scheduler.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateEtcdTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# etcd STIG Remediation\n\n")

	manifestPath := r.getManifestPath("etcd")

	for _, f := range findings {
		tasks.WriteString(fmt.Sprintf("# %s - %s\n", f.Control.ID, f.Control.Title))
		task := r.generateManifestPatchTask(f, manifestPath)
		tasks.WriteString(task)
		tasks.WriteString("\n")
	}

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "etcd.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateKubeletTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# Kubelet STIG Remediation\n\n")

	kubeletConfigPath := r.getKubeletConfigPath()

	for _, f := range findings {
		tasks.WriteString(fmt.Sprintf("# %s - %s\n", f.Control.ID, f.Control.Title))
		task := r.generateKubeletConfigTask(f, kubeletConfigPath)
		tasks.WriteString(task)
		tasks.WriteString("\n")
	}

	// Restart kubelet after changes
	tasks.WriteString("- name: Restart kubelet to apply changes\n")
	tasks.WriteString("  systemd:\n")
	tasks.WriteString("    name: kubelet\n")
	tasks.WriteString("    state: restarted\n")
	tasks.WriteString("  when: kubelet_config_changed | default(false)\n")

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "kubelet.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateGeneralTasks(findings []models.Finding) error {
	var tasks strings.Builder

	tasks.WriteString("---\n")
	tasks.WriteString("# General Cluster STIG Remediation\n\n")

	for _, f := range findings {
		tasks.WriteString(fmt.Sprintf("# %s - %s\n", f.Control.ID, f.Control.Title))

		switch {
		case strings.Contains(f.Details, "NetworkPolicies"):
			tasks.WriteString(r.generateNetworkPolicyTask(f))
		case strings.Contains(f.Details, "Pod Security"):
			tasks.WriteString(r.generatePodSecurityTask(f))
		default:
			tasks.WriteString(fmt.Sprintf("# TODO: Manual remediation required for %s\n", f.Control.ID))
			tasks.WriteString(fmt.Sprintf("# Details: %s\n\n", f.Details))
		}
	}

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "tasks")
	return os.WriteFile(filepath.Join(roleDir, "general.yml"), []byte(tasks.String()), 0600)
}

func (r *Remediator) generateHandlers() error {
	handlers := `---
# Handlers for STIG Remediation

- name: Restart kubelet
  systemd:
    name: kubelet
    state: restarted
    daemon_reload: yes

- name: Wait for API server
  command: kubectl get nodes
  register: result
  until: result.rc == 0
  retries: 30
  delay: 10
  changed_when: false
`

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "handlers")
	return os.WriteFile(filepath.Join(roleDir, "main.yml"), []byte(handlers), 0600)
}

func (r *Remediator) generateDefaults() error {
	defaults := `---
# Default variables for STIG Remediation

# Backup configurations before making changes
stig_backup_configs: true

# Kubernetes manifests directory
stig_manifests_dir: /etc/kubernetes/manifests

# Kubelet config path
stig_kubelet_config: /var/lib/kubelet/config.yaml

# API Server settings
stig_apiserver_anonymous_auth: "false"
stig_apiserver_profiling: "false"
stig_apiserver_audit_log_path: "/var/log/kubernetes/audit/audit.log"
stig_apiserver_audit_log_maxage: "30"
stig_apiserver_audit_log_maxbackup: "10"
stig_apiserver_audit_log_maxsize: "100"
stig_apiserver_tls_min_version: "VersionTLS12"

# TLS cipher suites (STIG-approved)
stig_tls_cipher_suites: >-
  TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
  TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
  TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
  TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

# Controller Manager settings
stig_controller_profiling: "false"
stig_controller_bind_address: "127.0.0.1"

# Scheduler settings
stig_scheduler_profiling: "false"
stig_scheduler_bind_address: "127.0.0.1"

# Kubelet settings
stig_kubelet_anonymous_auth: false
stig_kubelet_authorization_mode: "Webhook"
stig_kubelet_read_only_port: 0
stig_kubelet_protect_kernel_defaults: true
`

	roleDir := filepath.Join(r.outputDir, "roles", "stig-remediation", "defaults")
	return os.WriteFile(filepath.Join(roleDir, "main.yml"), []byte(defaults), 0600)
}

func (r *Remediator) generateSTIGMapping(findings []models.Finding) error {
	var mapping strings.Builder

	mapping.WriteString("# STIG Control Mapping\n")
	mapping.WriteString("# Generated by StigKube\n")
	mapping.WriteString("# Maps STIG controls to remediation tasks\n\n")

	mapping.WriteString("controls:\n")
	for _, f := range findings {
		mapping.WriteString(fmt.Sprintf("  - id: %s\n", f.Control.ID))
		mapping.WriteString(fmt.Sprintf("    stig_id: %s\n", f.Control.STIGID))
		mapping.WriteString(fmt.Sprintf("    severity: %s\n", f.Control.CAT))
		mapping.WriteString(fmt.Sprintf("    title: \"%s\"\n", f.Control.Title))
		mapping.WriteString(fmt.Sprintf("    status: %s\n", f.Status))
		mapping.WriteString(fmt.Sprintf("    details: \"%s\"\n", strings.ReplaceAll(f.Details, "\"", "'")))
		if f.NodeName != "" {
			mapping.WriteString(fmt.Sprintf("    node: %s\n", f.NodeName))
		}
		mapping.WriteString("\n")
	}

	return os.WriteFile(filepath.Join(r.outputDir, "stig-mapping.yml"), []byte(mapping.String()), 0600)
}

// Helper functions

func (r *Remediator) getManifestPath(component string) string {
	switch r.deploymentMethod {
	case "kubeadm", "kubespray":
		return fmt.Sprintf("/etc/kubernetes/manifests/%s.yaml", component)
	case "rke2":
		return fmt.Sprintf("/var/lib/rancher/rke2/agent/pod-manifests/%s.yaml", component)
	case "k3s":
		return fmt.Sprintf("/var/lib/rancher/k3s/agent/pod-manifests/%s.yaml", component)
	default:
		return fmt.Sprintf("/etc/kubernetes/manifests/%s.yaml", component)
	}
}

func (r *Remediator) getKubeletConfigPath() string {
	switch r.deploymentMethod {
	case "kubeadm", "kubespray":
		return "/var/lib/kubelet/config.yaml"
	case "rke2":
		return "/var/lib/rancher/rke2/agent/kubelet.kubeconfig"
	case "k3s":
		return "/var/lib/rancher/k3s/agent/kubelet.kubeconfig"
	default:
		return "/var/lib/kubelet/config.yaml"
	}
}

func (r *Remediator) generateManifestPatchTask(f models.Finding, manifestPath string) string {
	// Extract flag name and value from expected
	flag, value := parseExpectedFlag(f.ExpectedValue)
	if flag == "" || value == "" {
		return fmt.Sprintf("# TODO: Manual remediation required for %s\n# Expected: %s\n# See STIG control %s for guidance\n\n", f.Control.ID, f.ExpectedValue, f.Control.STIGID)
	}

	return fmt.Sprintf(`- name: "Remediate %s - %s"
  lineinfile:
    path: %s
    regexp: '^\s*- %s'
    line: '    - %s=%s'
    insertafter: '^\s*- kube-'
    state: present
  register: manifest_changed
  notify: Wait for API server
  tags: [%s]

`, f.Control.ID, sanitizeTitle(f.Control.Title), manifestPath, flag, flag, value, f.Control.ID)
}

func (r *Remediator) generateKubeletConfigTask(f models.Finding, configPath string) string {
	// Extract setting name and value
	setting, value := parseExpectedYAML(f.ExpectedValue)
	if setting == "" || value == "" {
		return fmt.Sprintf("# TODO: Manual remediation required for %s\n# Expected: %s\n# See STIG control %s for guidance\n\n", f.Control.ID, f.ExpectedValue, f.Control.STIGID)
	}

	return fmt.Sprintf(`- name: "Remediate %s - %s"
  lineinfile:
    path: %s
    regexp: '^%s:'
    line: '%s: %s'
    state: present
  register: kubelet_config_changed
  tags: [%s]

`, f.Control.ID, sanitizeTitle(f.Control.Title), configPath, setting, setting, value, f.Control.ID)
}

func (r *Remediator) generateNetworkPolicyTask(f models.Finding) string {
	return `- name: Apply default deny NetworkPolicy to namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: default-deny-all
        namespace: "{{ item }}"
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
  loop: "{{ namespaces_without_netpol | default([]) }}"
  tags: [network-policy]

`
}

func (r *Remediator) generatePodSecurityTask(f models.Finding) string {
	return `- name: Apply Pod Security Standards labels to namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
        labels:
          pod-security.kubernetes.io/enforce: "restricted"
          pod-security.kubernetes.io/audit: "restricted"
          pod-security.kubernetes.io/warn: "restricted"
  loop: "{{ namespaces_without_pss | default([]) }}"
  tags: [pod-security]

`
}

func filterByComponent(findings []models.Finding, component string) []models.Finding {
	var filtered []models.Finding
	for _, f := range findings {
		title := strings.ToLower(f.Control.Title)
		desc := strings.ToLower(f.Control.Description)
		details := strings.ToLower(f.Details)

		switch component {
		case "api":
			if strings.Contains(title, "api server") || strings.Contains(desc, "api server") ||
				strings.Contains(details, "apiserver") || strings.Contains(f.ExpectedValue, "--") {
				if !strings.Contains(title, "controller") && !strings.Contains(title, "scheduler") &&
					!strings.Contains(title, "etcd") && !strings.Contains(title, "kubelet") {
					filtered = append(filtered, f)
				}
			}
		case "controller":
			if strings.Contains(title, "controller") || strings.Contains(desc, "controller manager") {
				filtered = append(filtered, f)
			}
		case "scheduler":
			if strings.Contains(title, "scheduler") {
				filtered = append(filtered, f)
			}
		case "etcd":
			if strings.Contains(title, "etcd") || strings.Contains(desc, "etcd") {
				filtered = append(filtered, f)
			}
		case "kubelet":
			if strings.Contains(title, "kubelet") || strings.Contains(desc, "kubelet") ||
				strings.Contains(f.ExpectedValue, "readOnlyPort") ||
				strings.Contains(f.ExpectedValue, "tlsCertFile") {
				filtered = append(filtered, f)
			}
		case "general":
			if strings.Contains(details, "namespace") || strings.Contains(details, "networkpolic") ||
				strings.Contains(details, "pod security") {
				filtered = append(filtered, f)
			}
		}
	}
	return filtered
}

// stigCompliantValues maps flags/settings to their STIG-compliant values
var stigCompliantValues = map[string]string{
	// API Server flags
	"--anonymous-auth":              "false",
	"--insecure-port":               "0",
	"--profiling":                   "false",
	"--audit-log-path":              "{{ stig_apiserver_audit_log_path }}",
	"--audit-policy-file":           "/etc/kubernetes/audit-policy.yaml",
	"--audit-log-maxage":            "{{ stig_apiserver_audit_log_maxage }}",
	"--audit-log-maxbackup":         "{{ stig_apiserver_audit_log_maxbackup }}",
	"--audit-log-maxsize":           "{{ stig_apiserver_audit_log_maxsize }}",
	"--tls-min-version":             "VersionTLS12",
	"--tls-cipher-suites":           "{{ stig_tls_cipher_suites }}",
	"--encryption-provider-config":  "/etc/kubernetes/encryption-config.yaml",
	"--service-account-lookup":      "true",
	"--kubelet-https":               "true",
	"--authorization-mode":          "Node,RBAC",
	"--enable-admission-plugins":    "NodeRestriction,AlwaysPullImages",
	// Controller Manager flags
	"--use-service-account-credentials": "true",
	"--service-account-private-key-file": "/etc/kubernetes/pki/sa.key",
	"--root-ca-file":                     "/etc/kubernetes/pki/ca.crt",
	"--bind-address":                     "127.0.0.1",
	// etcd flags
	"--cert-file":             "/etc/kubernetes/pki/etcd/server.crt",
	"--key-file":              "/etc/kubernetes/pki/etcd/server.key",
	"--client-cert-auth":      "true",
	"--peer-cert-file":        "/etc/kubernetes/pki/etcd/peer.crt",
	"--peer-key-file":         "/etc/kubernetes/pki/etcd/peer.key",
	"--peer-client-cert-auth": "true",
}

// stigCompliantYAMLValues maps YAML settings to their STIG-compliant values
var stigCompliantYAMLValues = map[string]string{
	"authentication.anonymous.enabled": "false",
	"authorization.mode":               "Webhook",
	"authentication.x509.clientCAFile": "/etc/kubernetes/pki/ca.crt",
	"readOnlyPort":                     "0",
	"streamingConnectionIdleTimeout":   "5m",
	"protectKernelDefaults":            "true",
	"makeIPTablesUtilChains":           "true",
	"tlsCertFile":                      "/var/lib/kubelet/pki/kubelet.crt",
	"tlsPrivateKeyFile":                "/var/lib/kubelet/pki/kubelet.key",
}

func parseExpectedFlag(expected string) (string, string) {
	// Parse "--flag=value" or "--flag must be set" format
	if strings.Contains(expected, "=") {
		parts := strings.SplitN(expected, "=", 2)
		if len(parts) == 2 {
			return strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
		}
	}
	if strings.Contains(expected, " must be set") {
		flag := strings.TrimSuffix(expected, " must be set")
		flag = strings.TrimSpace(flag)
		// Look up the proper value for this flag
		if value, ok := stigCompliantValues[flag]; ok {
			return flag, value
		}
		return flag, ""
	}
	if strings.Contains(expected, " must not be ") {
		// Handle negation cases - extract just the flag
		parts := strings.SplitN(expected, " must not be ", 2)
		if len(parts) == 2 {
			flag := strings.TrimSpace(parts[0])
			if value, ok := stigCompliantValues[flag]; ok {
				return flag, value
			}
		}
	}
	if strings.Contains(expected, " must contain ") {
		parts := strings.SplitN(expected, " must contain ", 2)
		if len(parts) == 2 {
			flag := strings.TrimSpace(parts[0])
			if value, ok := stigCompliantValues[flag]; ok {
				return flag, value
			}
		}
	}
	return "", ""
}

func parseExpectedYAML(expected string) (string, string) {
	// Parse "setting: value" format
	if strings.Contains(expected, ": ") {
		parts := strings.SplitN(expected, ": ", 2)
		if len(parts) == 2 {
			return strings.TrimSpace(parts[0]), strings.TrimSpace(parts[1])
		}
	}
	if strings.Contains(expected, " must be set") {
		setting := strings.TrimSuffix(expected, " must be set")
		setting = strings.TrimSpace(setting)
		// Look up the proper value for this setting
		if value, ok := stigCompliantYAMLValues[setting]; ok {
			return setting, value
		}
		return setting, ""
	}
	return "", ""
}

func sanitizeTitle(title string) string {
	// Truncate and remove special characters for Ansible task names
	if len(title) > 60 {
		title = title[:60] + "..."
	}
	title = strings.ReplaceAll(title, "\"", "'")
	return title
}
